Interchangeable Spell Script
LeagueSandbox/LeagueSandbox-Default pull request #26
Opened 2017-04-11 04:14 UTC by MatthewFrench

Modified spell scripts to be more generic and interchangeable between passive, spells and buffs(and eventually gameobject AI). Blanked out all empty spells.

2017-04-18 06:50 UTC, MythicManiac requested changes
It feels silly to re-declare the same variables in every file, a way to inherit those properties should be looked into.

2017-04-18 06:50 UTC, MythicManiac commented on Buffs/LuluR/LuluR.cs
> +            spell = info.OwnerSpell;
These should be implemented in a way that we don't need to re-declare them in every spell. Maybe add a property to a base class

2017-04-18 06:54 UTC, MythicManiac commented on Buffs/LuluR/LuluR.cs
> +            spell = info.OwnerSpell;
Adding to this: it cannot be done with an interface, but if an interface isn't necessary we might want to just roll with abstract. Optionally we could add an abstract class that extends from the interface if a scenario like that would make more sense.

For example:
`IGameScript`
`AbstractGameScript : IGameScript`
`LuluR : AbstractGameScript`

Whatever is the most simple and flexible solution should be used, explore some options :)

2017-04-18 08:50 UTC, moonshadow565 commented
public string Foo { get; set; }
stuff like this can be used in interfaces

2017-04-18 08:56 UTC, MythicManiac commented
Using properties in interfaces won't implement them, it will just make it required for the subclasses to implement them AFAIK

2018-01-06 22:16 UTC, MythicManiac commented
Closing this as stale (almost a year old and needs huge rebase)

2018-01-06 22:16 UTC, closed without merging