Summoner spells
LeagueSandbox/LeagueSandbox-Default pull request #31
Opened 2017-04-23 18:36 UTC by xDawiss

Added all summoner spells that are possible atm (Ignite, Ghost, Revive, Smite, Clarity, Exhaust)

2017-04-23 19:03 UTC, Deudly requested changes
Please, follow the committing guidelines https://github.com/LeagueSandbox/GameServer/wiki/4.7.-Committing
By the way, if someone damages you, the Recall casting should stop

2017-04-24 05:23 UTC, MythicManiac requested changes
Nice work 👍 , though there are some issues

Aside from my comments, this doesn't follow the commit guidelines as @Deudly pointed out. (Your pull request has the proper format, but the commits you want to merge do not).

The format can be fixed by squash merging, but that leaves the recall issue.

I'd say we have 4 options here, which are:
1. Create an issue for the recall, squash merge this as it is now
2. Fix the recall issue in this PR, squash merge
3. Fix the recall issue and your commit format, merge
4. Fix your commit format and create an issue for recall, merge

Up to you which one, though I'd prefer you address my comments regardless which option you choose :)

2017-04-24 05:23 UTC, MythicManiac commented on Champions/Global/SummonerHaste.cs
> +
Unnecessary blank line

2017-04-24 05:23 UTC, MythicManiac commented on Champions/Global/SummonerHeal.cs
> +
Unnecessary blank lines

2017-04-24 05:23 UTC, MythicManiac commented on Champions/Global/SummonerMana.cs
> +
Unnecessary blank line

2017-04-24 05:23 UTC, MythicManiac commented on Champions/Global/SummonerMana.cs
> +
Unnecessary blank line (you have 2 in a row, remove at least the other :) )

2017-04-25 05:18 UTC, MythicManiac approved these changes

2017-04-25 05:18 UTC, MythicManiac commented
Issue created to #32, merging

2017-04-25 05:20 UTC, merged