Add some buff and champ skill
LeagueSandbox/LeagueSandbox-Default pull request #91
Opened 2018-11-01 00:23 UTC by requizm

Add some buff and champ skill

2018-11-01 00:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/LeagueSandbox/LeagueSandbox-Default?pullRequest=91) <br/>All committers have signed the CLA.

2019-02-02 20:26 UTC, danil179 commented
Code need to be updated cause we changed classes to interfaces.

2019-02-03 12:03 UTC, requizm commented
> Code need to be updated cause we changed classes to interfaces.

Okey, i will update as soon as possible

2019-02-03 14:34 UTC, requizm commented
> Code need to be updated cause we changed classes to interfaces.

I dont see changes. Everything is still the same. How can I contact you?

2019-02-04 20:07 UTC, danil179 commented
> 
> 
> > Code need to be updated cause we changed classes to interfaces.
> 
> I dont see changes. Everything is still the same. How can I contact you?

Join the discord mentioned in the README if you want to contact LS developers.

2019-02-04 20:10 UTC, danil179 requested changes
See my comment about the classes->interfaces change. You can also compare your classes to other classes in this repo, and better, you can run GameServer and test if your file compile.

2019-02-04 20:10 UTC, danil179 commented on Buffs/Snare/Snare.cs
> +        public void OnActivate(ObjAiBase unit, Spell ownerSpell)
All classes like `ObjAiBase` changed to interfaces like `IObjAiBase`.

2021-07-24 20:12 UTC, requizm commented
Deprecated issue

2021-07-24 20:12 UTC, closed without merging